version: 2

sources:
  - name: raw_data             # arbitrary name to reference later in SQL
    schema: ecommerce             # the dataset in BigQuery where your raw tables live
    database: durable-ripsaw-477914-g0  # your GCP project ID
    tables:
      - name: olist_customers
      - name: olist_geolocation
      - name: olist_order_items
      - name: olist_order_payments
      - name: olist_orders
      - name: olist_products
      - name: olist_sellers
      - name: product_category_name_translation
      - name: olist_order_reviews
