name: 'dbt_olist'
version: '1.0.0'
config-version: 2

profile: 'dbt_olist'

model-paths: ['models']
test-paths:  ['tests']
seed-paths:  ['seeds']
macro-paths: ['macros']

models:
  dbt_olist:
    staging:
      +materialized: view
    marts:
      +materialized: table
